name = "ExamFive"
uuid = "a7bfb819-e043-41e0-aa72-7bf737b32cac"
authors = ["Matt-Kandel"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
